# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: messagegate-poc

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 30
  environment:
    NODE_ENV: ${self:custom.env.NODE_ENV, 'development'}
    LOGGING_LEVEL: ${self:custom.env.LOGGING_LEVEL, 'info'}
    DATABASE_URI: ${self:custom.env.DATABASE_URI}
    DATABASE_SSL: ${self:custom.env.DATABASE_SSL}

functions:
  sms-get:
    handler: handlers/sms.get
    events:
      - http:
          path: sms/{id}
          method: get
          cors: true
          request:
            parameters: 
              paths: 
                id: true
  sms-post:
    handler: handlers/sms.post
    events:
      - http:
          path: sms
          method: post
          cors: true
  video-get:
    handler: handlers/video.get
    events:
      - http:
          path: video
          method: get
          cors: true
plugins:
  - serverless-offline
custom:
  serverless-offline:
    port: 5000
  env: ${file(./config/${self:provider.stage}.env.json)}

package:
  exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
    - .git/**
    - .vscode/**
    - coverage/**
    - tests/**